### ISSUE TITLE
Investigate support for rolling workspace deployments

### ISSUE THREAD

**Issue by amisevsk** [devfile/devworkspace-operator#244] opened 2021-01-15 02:39 UTC
## Description

Currently, the devworkspace operator runs workspaces in deployments with a `recreate` strategy. This is required because rolling deployments can hang if they mount a RWO volume, but it also means that most modifications to a devworkspace result in a short time where the workspace is offline. 

We should look into ways to configure whether rolling deployments should be used, and potentially enable rolling deployments automatically (if e.g. a workspace doesn't mount any PVCs or something like async storage is used).

**Comment by AObuchow** [comment] 2023-07-12 15:03
Closing this as it seems to be a duplicate of https://github.com/devfile/devworkspace-operator/issues/1045 which was resolved in https://github.com/devfile/devworkspace-operator/pull/1057

**Closed by AObuchow** 2023-07-12 15:03 UTC
