### ISSUE TITLE
DevWorkspace doesn't respect SSH key passphrase when git pushing changes from workspace

### ISSUE THREAD

**Issue by dmytro-ndp** [devfile/devworkspace-operator#1295] opened 2024-08-06 14:31 UTC
### Description

Related changes:
- https://github.com/devfile/devworkspace-operator/pull/1291, 
- https://github.com/eclipse-che/che-dashboard/pull/1157

#### Prerequisites: 
a) create SSH key with passphrase, using the command `ssh-keygen -b 2048 -t rsa -N "test"`
b) add it to the GitHub.com

#### Steps to reproduce:
1. Install Eclipse Che using User Dashboard https://quay.io/repository/eclipse/che-dashboard:pr-1157 with support of SSH key with passphrase
2. Open User Dashboard and add SSH key to the User Preferences.
3. Go to GitHub.com and get SSH link to any private repo using.
4. Go to "Eclipse Che -> Create workspace" page and create workspace using SSH link to the private repo.
5. Wait on workspace to be created, started, and project to be cloned.
6. Make changes in the project, commit them and push.
7. Go to workspace Terminal and try to push changes from there.

[Let Dev Spaces keep ssh passphrase for git.webm](https://github.com/user-attachments/assets/283bd203-e9b1-405f-abcb-673041559a8a)

### Expected behavior
Changes are pushed without errors or asking for passphrase.

### Actual behavior
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.08.06-14_39_32.webm](https://github.com/user-attachments/assets/3ad32dc3-25c2-49a4-bc3a-84b7d1da3ac3)

#### At the step 6
there was an error `Git: Warning: Permanently added the ECDSA host key for IP address '140.82.112.3' to the list of known hosts.` when tried to push changes to the repo using _Source Control_ view of _VS Code Editor_.
**_git-error log_**:
```
> git pull --tags origin main
Warning: Permanently added the ECDSA host key for IP address '140.82.112.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
![Screenshot from 2024-08-06 14-42-49](https://github.com/user-attachments/assets/63400a06-0172-48a5-8676-77da128a0270)

#### At the step 7
there was a request to enter passphrase for key '/etc/ssh/dwo_ssh_key":
![Screenshot from 2024-08-06 14-42-00](https://github.com/user-attachments/assets/187439ce-c317-4e07-9d5e-15fcc875c967)

**Comment by vinokurig** [comment] 2024-08-06 14:47
@AObuchow I believe that the problem is in the DWO side indeed. From the recording we see that the git push command called from terminal invokes the default ssh-askpass tool. Looks like we need to propagate the `ssh-askpass.sh` script to the workspace container as well.

**Comment by AObuchow** [comment] 2024-08-06 14:47
I believe the issue with git pushing from terminal prompting the user for the passphrase is because we do not have the required ssh-add environment variables injected into the workspace containers ([only the project clone container has them](https://github.com/devfile/devworkspace-operator/pull/1291/files#diff-aceff75e7200d60a46c47d68d39c072947f71ea9f0e7a4f2b9549438245a8b34R48-R49)).

We could either add the `DISPLAY` & ` SSH_ASKPASS` environment variables to all devworkspace containers, or try to add it only to the tooling container, similar to how we infer the tooling container component [when determining the image](https://github.com/devfile/devworkspace-operator/pull/1251/files#diff-f1f3498fd50bbc235d4d09f5f5485a91f5a4a5cfeb20b127c96fc849a30ba56bR217-R241) for the persistent-home-init-container.

@vinokurig @dkwon17 any thoughts?

**Comment by AObuchow** [comment] 2024-08-06 14:48
> @AObuchow I believe that the problem is in the DWO side indeed. From the recording we see that the git push command called from terminal invokes the default ssh-askpass tool. Looks like we need to propagate the `ssh-askpass.sh` script to the workspace container as well.

My thoughts exactly :) I was just about to finish writing my comment when you posted your comment.

**Comment by AObuchow** [comment] 2024-08-07 16:20
@vinokurig, here are some thoughts on where in the codebase we could make the required changes:
- We could inject the required `DISPLAY` & `SSH_ASKPASS` environment variables to the workspace containers in [`/pkg/library/env/workspaceenv.go`](https://github.com/devfile/devworkspace-operator/blob/main/pkg/library/env/workspaceenv.go). A new function (something like `addSSHEnvironmentVariables()`) could be made to inject these environment variables, or we could potentially use the `commonEnvironmentVariables()` [function](https://github.com/devfile/devworkspace-operator/blob/main/pkg/library/env/workspaceenv.go#L61-L88).
- The code related to injecting `ssh-askpass.sh` into the workspace containers could probably be added in its own file in [`/pkg/provision/`](https://github.com/devfile/devworkspace-operator/tree/main/pkg/provision), e.g.` /pkg/provision/ssh/`. Alternatively, it could go into [`/pkg/provision/workspace/`](https://github.com/devfile/devworkspace-operator/tree/main/pkg/provision/workspace).
  - You will probably have to call your function that injects `ssh-askpass.sh` in the main reconcile function (unless there's a better place for this). We did [something similar](https://github.com/devfile/devworkspace-operator/pull/1065/files#diff-05e72230161a4d41c5a27fb453041c78839c193a9ddcb5066b1cb62c5a399529R321-R325) for injecting service account tokens into the workspace.
    - I believe you'll have to create a volume and volumeMount for mounting the `ssh-askpass.sh` script, and then create a configmap on the cluster which mounts into the volume and contains the `ssh-askpass.sh` contents as its data. 
    - Here's an [example](https://github.com/devfile/devworkspace-operator/blob/main/pkg/provision/automount/configmap.go#L66-L147) of creating a volume and volumeMount for a configmap. Your implementation will be much simpler however: we need to create a simple volume that mounts at a specific path `/usr/local/bin/ssh-askpass.sh` and add it to the workspace's pod additions (like we do for the [serviceAccountToken volumes](https://github.com/devfile/devworkspace-operator/pull/1065/files#diff-8bf1cd053d0fe47f488d52fbf2cd7173a1eae146960a2c2be1dea6d71cc215beR30-R38)) 
    - Here's an [example](https://github.com/devfile/devworkspace-operator/blob/main/pkg/provision/automount/templates.go#L98-L111) of creating a configmap that has some data (again, this example is more complex than the current case but should give some ideas).

**Comment by AObuchow** [comment] 2024-08-07 16:24
Lastly, something that slipped my mind during the review of your [original PR for supporting ssh passphrases](https://github.com/devfile/devworkspace-operator/pull/1291): instead of adding the ssh-add environment variables directly [into the project clone image](https://github.com/devfile/devworkspace-operator/pull/1291/files#diff-aceff75e7200d60a46c47d68d39c072947f71ea9f0e7a4f2b9549438245a8b34R47-R49), we could add them into the [container's environment variables](https://github.com/devfile/devworkspace-operator/blob/main/pkg/library/env/workspaceenv.go#L50-L59). An argument against this approach however, is that users who [provide their own project clone container image](https://github.com/devfile/devworkspace-operator/pull/1091) might not want these environment variables set for them.

I don't think we need to do anything about this, but I wanted to mention this here incase the topic ever comes up.

**Comment by ibuziuk** [comment] 2024-08-08 07:26
moving to the next release for 3.17 - [https://issues.redhat.com/browse/CRW-6614?focusedId=25289708&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#commen[…]289708](https://issues.redhat.com/browse/CRW-6614?focusedId=25289708&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-25289708)

**Closed** 2024-09-09 20:04 UTC
